{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "fr-FR",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/HK\\HK_SQL;ContosoRetailDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "HK\\HK_SQL",
            "database": "ContosoRetailDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductLabel",
            "dataType": "string",
            "sourceColumn": "ProductLabel"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "ProductDescription",
            "dataType": "string",
            "sourceColumn": "ProductDescription"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer"
          },
          {
            "name": "BrandName",
            "dataType": "string",
            "sourceColumn": "BrandName"
          },
          {
            "name": "ClassID",
            "dataType": "string",
            "sourceColumn": "ClassID"
          },
          {
            "name": "ClassName",
            "dataType": "string",
            "sourceColumn": "ClassName"
          },
          {
            "name": "StyleID",
            "dataType": "string",
            "sourceColumn": "StyleID"
          },
          {
            "name": "StyleName",
            "dataType": "string",
            "sourceColumn": "StyleName"
          },
          {
            "name": "ColorID",
            "dataType": "string",
            "sourceColumn": "ColorID"
          },
          {
            "name": "ColorName",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "SizeUnitMeasureID",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureID"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "WeightUnitMeasureID",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureID"
          },
          {
            "name": "UnitOfMeasureID",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasureID"
          },
          {
            "name": "UnitOfMeasureName",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasureName"
          },
          {
            "name": "StockTypeID",
            "dataType": "string",
            "sourceColumn": "StockTypeID"
          },
          {
            "name": "StockTypeName",
            "dataType": "string",
            "sourceColumn": "StockTypeName"
          },
          {
            "name": "UnitCost",
            "dataType": "decimal",
            "sourceColumn": "UnitCost"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "AvailableForSaleDate",
            "dataType": "dateTime",
            "sourceColumn": "AvailableForSaleDate"
          },
          {
            "name": "StopSaleDate",
            "dataType": "dateTime",
            "sourceColumn": "StopSaleDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "ImageURL",
            "dataType": "string",
            "sourceColumn": "ImageURL"
          },
          {
            "name": "ProductURL",
            "dataType": "string",
            "sourceColumn": "ProductURL"
          },
          {
            "name": "ETLLoadID",
            "dataType": "int64",
            "sourceColumn": "ETLLoadID"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          },
          {
            "name": "UpdateDate",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/HK\\HK_SQL;ContosoRetailDW\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hr BrandName ColourName",
            "levels": [
              {
                "name": "ColorName",
                "ordinal": 0,
                "column": "ColorName"
              },
              {
                "name": "Manufacturer",
                "ordinal": 1,
                "column": "Manufacturer"
              },
              {
                "name": "ProductName",
                "ordinal": 2,
                "column": "ProductName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryLabel",
            "dataType": "string",
            "sourceColumn": "ProductCategoryLabel"
          },
          {
            "name": "ProductCategoryName",
            "dataType": "string",
            "sourceColumn": "ProductCategoryName"
          },
          {
            "name": "ProductCategoryDescription",
            "dataType": "string",
            "sourceColumn": "ProductCategoryDescription"
          },
          {
            "name": "ETLLoadID",
            "dataType": "int64",
            "sourceColumn": "ETLLoadID"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          },
          {
            "name": "UpdateDate",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/HK\\HK_SQL;ContosoRetailDW\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data]",
                "in",
                "    dbo_DimProductCategory"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProductSubcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryLabel",
            "dataType": "string",
            "sourceColumn": "ProductSubcategoryLabel"
          },
          {
            "name": "ProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "ProductSubcategoryName"
          },
          {
            "name": "ProductSubcategoryDescription",
            "dataType": "string",
            "sourceColumn": "ProductSubcategoryDescription"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ETLLoadID",
            "dataType": "int64",
            "sourceColumn": "ETLLoadID"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          },
          {
            "name": "UpdateDate",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/HK\\HK_SQL;ContosoRetailDW\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data]",
                "in",
                "    dbo_DimProductSubcategory"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "SalesKey",
            "dataType": "int64",
            "sourceColumn": "SalesKey"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "sourceColumn": "DateKey"
          },
          {
            "name": "channelKey",
            "dataType": "int64",
            "sourceColumn": "channelKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "UnitCost",
            "dataType": "decimal",
            "sourceColumn": "UnitCost"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "SalesQuantity",
            "dataType": "int64",
            "sourceColumn": "SalesQuantity"
          },
          {
            "name": "ReturnQuantity",
            "dataType": "int64",
            "sourceColumn": "ReturnQuantity"
          },
          {
            "name": "ReturnAmount",
            "dataType": "decimal",
            "sourceColumn": "ReturnAmount"
          },
          {
            "name": "DiscountQuantity",
            "dataType": "int64",
            "sourceColumn": "DiscountQuantity"
          },
          {
            "name": "DiscountAmount",
            "dataType": "decimal",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "TotalCost",
            "dataType": "decimal",
            "sourceColumn": "TotalCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "ETLLoadID",
            "dataType": "int64",
            "sourceColumn": "ETLLoadID"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          },
          {
            "name": "UpdateDate",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDate"
          },
          {
            "type": "calculated",
            "name": "Sales Amount",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": " FactSales[SalesQuantity]*FactSales[UnitPrice]",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/HK\\HK_SQL;ContosoRetailDW\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data]",
                "in",
                "    dbo_FactSales"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of Sales Amount",
            "expression": "SUM([Sales Amount])",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "SumDiscountAmount",
            "expression": "SUM([DiscountAmount])",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Cost",
            "expression": " SUMX(FactSales,FactSales[UnitCost]*Factsales[SalesQuantity])",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margin",
            "expression": [
              " FactSales[Sum of Sales Amount]- [Total Cost]",
              ""
            ],
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margin %",
            "expression": " [Margin]/[Sum of Sales Amount]",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "kpi": {
              "targetExpression": "'FactSales'[AVG%]",
              "targetFormatString": "0.00 %;-0.00 %;0.00 %",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='FactSales'[Margin %]/'FactSales'[_Margin % Goal] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.95,-1,",
                "\t                If(x<1.05,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "105"
                }
              ]
            }
          },
          {
            "name": "AVG%",
            "expression": " CALCULATE([Margin %],ALLSELECTED())",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          }
        ]
      },
      {
        "name": "CalculatedTable 1",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ColorName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DimProduct[ColorName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Total Sales",
            "dataType": "decimal",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Total Sales]",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "ADDCOLUMNS(VALUES(DimProduct[ColorName]), \"Total Sales\", [Sum of Sales Amount])"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "57c2e23d-1ca9-4b9f-b476-7ff3c97648b5",
        "fromTable": "DimProduct",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "d3a5e4d3-0141-4e91-af8f-8c04e090be88",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "8d50ced1-d096-4d16-ab53-c7af9f010cc4",
        "fromTable": "DimProductSubcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "DimProductCategory",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "3a1110fa-02e0-430d-a9db-be7594f1df71",
        "fromTable": "DimProduct",
        "fromColumn": "ColorName",
        "toTable": "CalculatedTable 1",
        "toColumn": "ColorName"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}